require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'HalalMkt' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # use_frameworks!
  pod 'RNInputMask', :path => '../node_modules/react-native-text-input-mask/ios/InputMask'

  target 'HalalMktTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'HalalMkt-tvOS' do
  # Pods for HalalMkt-tvOS

  target 'HalalMkt-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
