export const START_LOADING = "START_LOADING";
export const VENDORS_LIST = "VENDORS_LIST";
export const VENDORS_STOCK = "VENDORS_STOCK";
export const VENDORS_LIST_ERROR = "VENDORS_LIST_ERROR";
export const VENDORS_STOCK_UPDATE = "VENDORS_STOCK_UPDATE";
